#!/usr/bin/python3
#-*- coding:UTF-8 -*-

import telnetlib
import time
import re
import threading

def Console_Server_Login(HOST, Port, Username, Password):
    try:
        tn_1 = telnetlib.Telnet(HOST,Port)    # Login to Console server
        tn_1.set_debuglevel(2)
        Console_Server_Login_Result = tn_1.read_until(b'Login : ', 1)
        time.sleep(5) # 20180304 21:45
        if re.search('Closing', str(Console_Server_Login_Result)):
            print("Port is in use!!!!!!")
            tn_1.close()
            #time.sleep(60)
            #Console_Server_Login(HOST, Port, Username, Password)
        else:
            tn_1.write(Username.encode('utf-8') + b"\n")
            time.sleep(3)
            tn_1.read_until(b'Password : ')
            time.sleep(3)
            tn_1.write(Password.encode('utf-8') + b"\n")
            time.sleep(5)
            #tn_1.write(b'\n').
            tn_1.read_until(b"root")   # Login as 'root' account, key word 'root' will display from the window
            tn_1.write(b"\n")
            time.sleep(2)
            tn_1.write(b"\n")
            time.sleep(3)
            tn_1.close()

    except:
        print("!!!!!!!!!!!!!!!!!Abnormal but please wait!!!!!!!!!!!!!!!!!!!!!!!!!!")
        tn_1.close()
        time.sleep(60)
        Console_Server_Login(HOST, Port, Username, Password)

if __name__ == '__main__':
    HOST = "10.75.X.X"
    port = [7001,7002,7003,7004,7005,7006,7007,7008,7009,7018,7019,7021,7020,7022,7024]
    #port = [7001]
    Username = 'root'
    Password = 'XXXXXX'
    for Port in port:
        t = threading.Thread(target=Console_Server_Login,args=(HOST,Port,Username,Password))
