#!/usr/bin/python3
#-*- coding:UTF-8 -*-

import telnetlib
import time
import re
import threading

def Device_Rescue_Config(Port):
    Device_Rescue_Config_filename = r"./"+str(Port)+r"_Config.txt"
    return Device_Rescue_Config_filename

def Console_Server_Login(HOST, Port, Username, Password):
    try:
        tn_1 = telnetlib.Telnet(HOST,Port)    # Login to Console server
        tn_1.set_debuglevel(2)
        Console_Server_Login_Result = tn_1.read_until(b'Login : ', 1)
        time.sleep(5) # 20180304 21:45
        if re.search('Closing', str(Console_Server_Login_Result)):
            print("Port is in use!!!!!!")
            tn_1.close()
            time.sleep(60)
            Console_Server_Login(HOST, Port, Username, Password)
        else:
            tn_1.write(Username.encode('utf-8') + b"\n")
            time.sleep(3)
            tn_1.read_until(b'Password : ')
            time.sleep(3)
            tn_1.write(Password.encode('utf-8') + b"\n")
            #time.sleep(5)
            #tn_1.write(b' ')
            #tn_1.write(b'\n')
            #tn_1.read_until(b"root")   # Login as 'root' account, key word 'root' will display from the window
            #tn_1.write(b"\n")
            #tn_1.write(b'\x03')   # Input 'ctrl+c' to interrupt the ping testing it there has
            tn_1.write(b"\n")
            #tn_1.write(b' ')
            Device_Login_Result = tn_1.read_until(b'login:', 3)   # Device status is "login:)
            #time.sleep(3)  # 20180228 15:51 added
            time.sleep(3)
            if "login" in str(Device_Login_Result):
                tn_1.write(Username.encode('utf-8')+b'\n')
                tn_1.read_until(b'Password', 1)
                tn_1.write(Password.encode('utf-8')+b'\n')
                time.sleep(2)  # Added 201803011334
                tn_1.write(b'\n')
                #time.sleep(2)
                #tn_1.write(b'\x03')
                tn_1.write(b'cli\n')
                tn_1.write(b' ')
                tn_1.write(b'config\n')
                time.sleep(3)
                tn_1.write(b'delete')
                tn_1.write(b'\n')
                tn_1.read_until(b'yes,')
                time.sleep(2)
                tn_1.write(b'yes\n')
                tn_1.write(b'run request system storage cleanup\n')
                storage_result = tn_1.read_until(b'yes')
                while True:
                    time.sleep(20)
                    if re.search('yes', str(storage_result)):
                        tn_1.write(b'yes\n')
                        time.sleep(2)
                        with open(Device_Rescue_Config(Port), 'rb') as f:
                            for line in f.readlines():
                                tn_1.write(line)
                                time.sleep(1)
                        tn_1.write(b'\n')
                        tn_1.write(b'commit\n')
                        time.sleep(5)
                        tn_1.write(b'run request system halt' + b'\n')
                        tn_1.read_until(b'yes,')
                        tn_1.write(b'yes' + b'\n')
                        tn_1.close()
                        break
                    elif re.search('more', str(storage_result)):
                        for i in range(5):
                            tn_1.write(b' ')
                            time.sleep(2)
                        continue
            elif re.search('loader', str(Device_Login_Result)):
                tn_1.write(b'reboot'+b'\n')
                time.sleep(300)
                tn_1.read_until(b'login:', 3)
                tn_1.write(Username.encode('utf-8') + b'\n')
                tn_1.read_until(b'Password', 1)
                tn_1.write(Password.encode('utf-8') + b'\n')
                time.sleep(2)  # Added 201803011334
                tn_1.write(b'\n')
                tn_1.write(b'\x03')
                tn_1.write(b'cli\n')
                tn_1.write(b' ')
                tn_1.write(b'config\n')
                tn_1.write(b'delete')
                tn_1.write(b'\n')
                tn_1.read_until(b'yes,')
                time.sleep(2)
                tn_1.write(b'yes\n')
                tn_1.write(b'run request system storage cleanup\n')
                storage_result = tn_1.read_until(b'yes')
                while True:
                    time.sleep(20)
                    if re.search('yes', str(storage_result)):
                        tn_1.write(b'yes\n')
                        time.sleep(2)
                        with open(Device_Rescue_Config(Port), 'rb') as f:
                            for line in f.readlines():
                                tn_1.write(line)
                                time.sleep(1)
                        tn_1.write(b'\n')
                        tn_1.write(b'commit\n')
                        time.sleep(5)
                        tn_1.write(b'run request system halt' + b'\n')
                        tn_1.read_until(b'yes,')
                        tn_1.write(b'yes' + b'\n')
                        tn_1.close()
                        break
                    elif re.search('more', str(storage_result)):
                        for i in range(5):
                            tn_1.write(b' ')
                            time.sleep(2)
                        continue

            elif re.search('root(.*)>', str(Device_Login_Result)):
                time.sleep(1) # Added 201803011444 try to collect show result better
                tn_1.write(b'\n')
                tn_1.write(b' ')
                tn_1.write(b'config\n')
                tn_1.write(b'delete')
                tn_1.write(b'\n')
                tn_1.read_until(b'yes,')
                time.sleep(2)
                tn_1.write(b'yes\n')
                tn_1.write(b'run request system storage cleanup\n')
                storage_result = tn_1.read_until(b'yes')
                while True:
                    time.sleep(20)
                    if re.search('yes', str(storage_result)):
                        tn_1.write(b'yes\n')
                        time.sleep(2)
                        with open(Device_Rescue_Config(Port), 'rb') as f:
                            for line in f.readlines():
                                tn_1.write(line)
                                time.sleep(1)
                        tn_1.write(b'\n')
                        tn_1.write(b'commit\n')
                        time.sleep(5)
                        tn_1.write(b'run request system halt' + b'\n')
                        tn_1.read_until(b'yes,')
                        tn_1.write(b'yes' + b'\n')
                        tn_1.close()
                        break
                    elif re.search('more', str(storage_result)):
                        for i in range(5):
                            tn_1.write(b' ')
                            time.sleep(2)
                        continue
            elif re.search('root(.*)%', str(Device_Login_Result)):
                time.sleep(1) # Added 201803011443 try to storage show result better
                tn_1.write(b'\n')
                tn_1.write(b' ')
                tn_1.write(b'cli\n')
                tn_1.write(b' ')
                tn_1.write(b'config\n')
                tn_1.write(b'delete')
                tn_1.write(b'\n')
                tn_1.read_until(b'yes,')
                time.sleep(2)
                tn_1.write(b'yes\n')
                tn_1.write(b'run request system storage cleanup\n')
                storage_result = tn_1.read_until(b'yes')
                while True:
                    time.sleep(20)
                    if re.search('yes', str(storage_result)):
                        tn_1.write(b'yes\n')
                        time.sleep(2)
                        with open(Device_Rescue_Config(Port), 'rb') as f:
                            for line in f.readlines():
                                tn_1.write(line)
                                time.sleep(1)
                        tn_1.write(b'\n')
                        tn_1.write(b'commit\n')
                        time.sleep(5)
                        tn_1.write(b'run request system halt' + b'\n')
                        tn_1.read_until(b'yes,')
                        tn_1.write(b'yes' + b'\n')
                        tn_1.close()
                        break
                    elif re.search('more', str(storage_result)):
                        for i in range(5):
                            tn_1.write(b' ')
                            time.sleep(2)
                        continue
            elif re.search('root(.*)#', str(Device_Login_Result)):
                time.sleep(1) # Added 201803011445 try to storage the show result better
                tn_1.write(b'\n')
                tn_1.write(b'delete')
                tn_1.write(b'\n')
                tn_1.read_until(b'yes,')
                time.sleep(2)
                tn_1.write(b'yes\n')
                tn_1.write(b'run request system storage cleanup\n')
                storage_result = tn_1.read_until(b'yes')
                while True:
                    time.sleep(20)
                    if re.search('yes', str(storage_result)):
                        tn_1.write(b'yes\n')
                        time.sleep(2)
                        with open(Device_Rescue_Config(Port), 'rb') as f:
                            for line in f.readlines():
                                tn_1.write(line)
                                time.sleep(1)
                        tn_1.write(b'\n')
                        tn_1.write(b'commit\n')
                        time.sleep(5)
                        tn_1.write(b'run request system halt' + b'\n')
                        tn_1.read_until(b'yes,')
                        tn_1.write(b'yes' + b'\n')
                        tn_1.close()
                        break
                    elif re.search('more', str(storage_result)):
                        for i in range(5):
                            tn_1.write(b' ')
                            time.sleep(2)
                        continue
            else:
                print("Console cable disconneted or device in booting process")
                tn_1.close()
                time.sleep(50400)
                Console_Server_Login(HOST, Port, Username, Password)
    except:
        print("!!!!!!!!!!!!!!!!!Abnormal but please wait!!!!!!!!!!!!!!!!!!!!!!!!!!")
        tn_1.close()
        time.sleep(60)
        Console_Server_Login(HOST, Port, Username, Password)

if __name__ == '__main__':
    HOST = "10.75.X.X"
    port = [7001,7002,7003,7004,7005,7006,7007,7008,7009,7018,7019,7021,7020,7022,7024]
    #port = [7005]
    Username = 'root'
    Password = 'root123'
    for Port in port:
        t = threading.Thread(target=Console_Server_Login,args=(HOST,Port,Username,Password))
        t.start()
